### ISSUE TITLE
v.1.1.0 Roadmap

### ISSUE THREAD

**Issue by Jegethy** [Jegethy/mods#2]
## v.1.1.0 Roadmap

The checklists below outline the planned features for version 1.1.0 of the mod. It will be released once all features have been checked off. The list is in order of importance, from most to least important.

- [ ] Finish implementing accessory effects for the Accessorise mod
- [ ] Create item mods that can be socketed into Accessorise accessories
- [ ] Revert changes to crafting speed; selectively change crafting speed of some items
- [ ] Implement ranks 10 through 15 for all attributes
- [ ] Implement additional Extra Progression perks
- [ ] Balancing pass on Progression mod
- [ ] Tweak inventory sizes of vehicles
- [ ] Make updates to Grease Monkey perk
- [ ] Localisation Updates
